### ISSUE TITLE
Ajout de aria-current=page dans le menu

### ISSUE THREAD

**Issue by EmmanuelDemey** [EmmanuelDemey/GlobalIssueTracker#18]
# Informations générales

* URL du site : https://devfest.gdgnantes.com/

# Descriptions

Dans le menu, il faudrait ajouter un aria-current=page sur le lien correspondant à la page courante. 

![image](https://user-images.githubusercontent.com/555768/154523360-07322931-79d6-42e8-bf28-08675890e47f.png)

**Comment by ArtyMaury** [comment]
Hello,
On m'a dit que le problème était toujours d'actualité sur le nouveau site mais il ne me semble pas, ou alors je regarde pas au bon endroit, tu peux me confirmer la correction ou me dire où est le soucis stp ? 
Je suis pas bon en accessibilité mais j'ai bien l'intention d'améliorer tout ça avec la refonte du site !

**Comment by EmmanuelDemey** [comment]
@ArtyMaury C'est bon en fait :D 
J'ai ajouté le logo du Devfest Lille sur le README.md https://github.com/EmmanuelDemey/GlobalIssueTracker/blob/master/README.md

Si tu veux parler Accessibilité, n'hésite pas. Je suis dispo .
