### ISSUE TITLE
Un lien qui est visiblement désactivé ne l'est pas vraiment

### ISSUE THREAD

**Issue by EmmanuelDemey** [EmmanuelDemey/GlobalIssueTracker#45]
# Informations générales

* URL du site : https://bdxio.fr/

# Descriptions

Le bouton ci-dessous semble désactivé. Mais est toujours joignable via le clavier. Nous devons ajouter l'attribut disabled pour que cela corrige le problème

<img width="1362" alt="Capture d’écran 2023-05-11 à 13 30 54" src="https://github.com/EmmanuelDemey/GlobalIssueTracker/assets/555768/27de7078-e9bc-4b31-8611-5fa544b92260">

# Quelques Liens

**Comment by antoinechassagne** [comment]
C'est corrigé, merci pour votre retour 👍

**Comment by EmmanuelDemey** [comment]
@antoinechassagne pourquoi utilises tu un tabindex=-1 et pas un `disabled`?

**Comment by antoinechassagne** [comment]
C'est bon pour de vrai cette fois-ci 😅

**Comment by EmmanuelDemey** [comment]
C'est parfait. merci @antoinechassagne
